cache_type : "memcached"
memcached_host: "127.0.0.1"
memcached_port: 11211
redis_stream_hosts:
 - "127.0.0.1"
redis_stream_port: 6379
redis_password: null
redis_channel: "myapp-mc-main:purge"
data_directory: /var/cache/python-mc-relay
